### ISSUE TITLE
Can't declare GenericTemplate

### ISSUE THREAD

**Issue by parnus01** [rickydunlop/fbmessenger-node#51]
i try to declare GenericTemplate with this code 
```
 let __elements = [
                          new Element({
                            title: 'Title',
                            item_url: 'http://www.example.com',
                            image_url: 'http://www.example.com',
                            subtitle: 'Subtitle',
                            buttons: [
                              new Button({
                                type: 'web_url',
                                title: 'Button',
                                url: 'http://www.example.com',
                              }),
                            ]
                          })
                        ];

let test_generic = new GenericTemplate([__elements]);
```
but error throw 
```
Error: elements must be an array
at GenericTemplate.BaseTemplate (/user_code/node_modules/fbmessenger/dist/templates/BaseTemplate.js:9:13)
```

i already debug with Array.isArray() it return true 
Any ideas of what is going on?

**Comment by rickydunlop** [comment]
The GenericTemplate and most other functions in this library use [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring) for the parameters. 
So to pass elements to the template you need to do something like this

```js
const generic = new GenericTemplate({ elements: __elements });
```

You might find the [example](https://github.com/rickydunlop/fbmessenger-node/blob/master/example/index.js#L236) helpful

Also be careful that you don't wrap your `__elements` variable inside an extra array.
I noticed you were passing `[__elements]` but `__elements` is already an array due to `let __elements = [...]`
